name: generate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4

    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install LDoc
      run: luarocks install ldoc

    - name: Prepare Documentation
      run: |
        echo "- clean api -"

        rm -rf .git
        rm -rf .github

        python filter_ue4_macros.py
        python lua_code_highlight.py

        mkdir output

    - name: Generate LDoc Documentation
      run: ldoc . --dir output/docs

    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output/docs  # This must match `dir` in config.ld
        publish_branch: gh-pages
        force_orphan: true
