name: generate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build 💼
      run: |
        echo "- clone api -"
        git clone --depth 1 https://github.com/wavelet-noise/evospace-api.git source
        
        cd source
        
        echo "- clone doxy css -"
        
        git clone https://github.com/jothepro/doxygen-awesome-css.git
        cd doxygen-awesome-css
        git checkout v2.1.0
        
        echo "- finish -"
        
        cd ..
        
        ls -A
        
        realpath Doxyfile
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.4
      env:
        working-directory: 'source'
        doxyfile-path: 'source'
        
    - name: Deploy 🚀
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: source
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
