name: Generate Documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          pip install sphinx sphinx-lua-ls

      - name: Install Lua Language Server
        run: |
          git clone https://github.com/LuaLS/lua-language-server.git
          cd lua-language-server && ./make.sh

      - name: Generate JSON Documentation
        run: ./lua-language-server/bin/lua-language-server --export-documentation ./api ./output/docs.json

      - name: Build Documentation with Sphinx
        run: |
          sphinx-build -b html ./docs ./build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
